# Generated by Django 4.2.6 on 2023-12-27 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3e9b5d8-72ab-4ab2-acfc-333894da46dc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
