# Generated by Django 4.2.6 on 2023-12-27 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7e05024-de53-47a8-bf02-5de4a34e64b6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
