# Generated by Django 4.2.6 on 2023-12-14 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_groups_user_user_permissions_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e3db99e-497e-446f-83a1-7e1e99a6c628'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
