# Generated by Django 4.2.6 on 2023-12-14 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db4dda0c-2c93-43f3-9106-25f2a12bc0d1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
