# Generated by Django 4.2.6 on 2023-12-27 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c8cafc10-d39e-4ee3-9d0e-b3813475cdb1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
