# Generated by Django 4.2.6 on 2023-12-14 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ffffc7e2-a664-49e1-b9be-d09518da61e1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
