# Generated by Django 4.2.6 on 2023-12-14 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('631ebbfa-92a3-4359-a4cf-3194d45218f7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
