# Generated by Django 4.2.6 on 2023-12-28 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ecc7ac57-6a33-48ab-9df8-bc1796a13272'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
