# Generated by Django 4.2.6 on 2023-12-15 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('53aa50ac-c4df-454d-8df3-bc181ac18cfc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
