# Generated by Django 4.2.6 on 2023-12-28 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ff5b6d62-ae3a-42d8-9f51-099f77c8a572'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
