# Generated by Django 4.2.6 on 2023-12-15 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eb108bb5-3ac2-4cf6-9114-3fb5ea15a8ff'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
