# Generated by Django 4.2.6 on 2023-12-14 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a19f4c33-3e53-4ac6-9d43-496441f8ef17'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
