# Generated by Django 4.2.6 on 2023-12-28 22:11

import apps.task_manager.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowtask',
            name='order',
            field=apps.task_manager.fields.OrderField(),
        ),
    ]
