# Generated by Django 4.2.6 on 2023-12-28 22:43

import apps.task_manager.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_flowtask_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowtask',
            name='old_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowtask',
            name='order',
            field=apps.task_manager.fields.OrderField(blank=True),
        ),
    ]
