# Generated by Django 4.2.6 on 2023-12-14 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a850651-d40c-4d54-bb2d-34c51ab68d61'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
