# Generated by Django 4.2.6 on 2023-12-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_flowtask_old_order_alter_flowtask_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowtask',
            name='old_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
